### PR TITLE
Add stuff to readme

### PR DESCRIPTION
**Pull request by galenlynch**

### CODE REVIEW

**Review by jtyoung84 — APPROVED** [review]
I'll approve. The only suggestion I might make is to call "Non-goals" as "Secondary goals." I think it will be worthwhile to compress multiple videos in parallel.

**Comment by galenlynch** [comment]
Sorry non-goal is sacrificing video quality to save encoding time.

**Comment by galenlynch** [comment]
I can edit to clarify that.

**Comment by galenlynch** [comment]
My intent is to educate future and current maintainers about some surprising features of video encoders. For a given compression level, or even encoder and set of parameters, there are some changes you can make to decrease encoding time that also decrease the quality of the resulting artifact. For example, using a GPU encoder, or changing the CPU preset from slow to fast. Both of these speed up the encode (great!) but at the expense of the quality of resulting artifact (not great). It's also not that clear without doing some benchmarks of visual quality that the speedup comes at a permanent cost.

Since we are producing permanent artifacts and destroying the original, and the encode is a one-time computational cost, I just want to be clear that we should choose better artifacts over shorter run times.

**Comment by jtyoung84** [comment]
> My intent is to educate future and current maintainers about some surprising features of video encoders. For a given compression level, or even encoder and set of parameters, there are some changes you can make to decrease encoding time that also decrease the quality of the resulting artifact. For example, using a GPU encoder, or changing the CPU preset from slow to fast. Both of these speed up the encode (great!) but at the expense of the quality of resulting artifact (not great). It's also not that clear without doing some benchmarks of visual quality that the speedup comes at a permanent cost.
> 
> Since we are producing permanent artifacts and destroying the original, and the encode is a one-time computational cost, I just want to be clear that we should choose better artifacts over shorter run times.

Sounds good. Feel free to merge the update to the README file whenever it's ready.

**Pull request merged**
